version: '3.0'

services:
  dbsql:
    image: mysql:8.0
    ports:
      - "6603:3306"
    volumes:
      - sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: mailService
      MYSQL_USER: esuarez-mail
      MYSQL_PASSWORD: esPass

  dbnon-sql:
    image: mongo:3-xenial
    ports:
      - "2707:27017"
    volumes:
      # - ./src/main/resources/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - non-sql-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mail
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPass

volumes:
  sql-data:
  non-sql-data:
