server:
  port: 8282

spring:
  data:
    mongodb:
      host: localhost
      port: 2707
      database: test
      username: esuarez
      password: pass
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
