server:
  port: 8181

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:6603/mailService?useUnicode=true;characterEncoding=UTF-8
    username: esuarez-mail
    password: esPass

  messages:
    encoding: UTF-8

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

