server:
  port: 8282

spring:
  data:
    mongodb:
      host: localhost
      port: 2707
      database: mail
      username: esuarez
      password: esPass

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
